### ISSUE TITLE
Heresy

### ISSUE THREAD

**Issue by CitizenPoe** [Danieljb5/Loredustry#1]
Upon entering the system to perform exterminatus in the Emperor's name, we were stopped. we believe the heretical xenos Tyranids are active in this sector. requesting Astartes reinforcement. Forward guard has been deployed and will purge the xenos until the last man. basically when logging in after installing mod get errors, a bunch

![Screenshot_20210525-184133_Mindustry](https://user-images.githubusercontent.com/83760252/119536779-bcc30a00-bd89-11eb-85b1-cb635d1df1d8.jpg)
.

**Comment by CitizenPoe** [comment]
Edit: only saw after the fact the project is on hold. my bad. May the Emperor protect.

**Comment by Danieljb5** [comment]
Sorry about the late response, my friend who works on this with me deleted some of the items that other content depends on for some reason.

**Comment by CitizenPoe** [comment]
no problem, I saw the project is on pause. it's no hassle, if you do replace it or post an update, reply to this comment and I'll re download and test it for you.

**Comment by Danieljb5** [comment]
Thanks. I have stamped out a few bugs so far but the planet generation is still a bit wonky
